routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Route::get('locale/{locale}', function ($locale){
        Session::put('locale', $locale);
        return redirect()->back();
    });
/*--------------------------------------------------------------------------
| User Routes
|--------------------------------------------------------------------------*/
Route::any('/', 'DashboardController@index')->name('Dashboard');
Route::any('/home', 'HomeController@index')->name('Home')->middleware(['auth', 'verified']);
Route::resource('commission','CommissionController')->middleware(['auth', 'verified']);
Route::resource('objekt','ObjectsController')->middleware(['auth', 'verified']);
Route::get('edit/user', 'UserController@edit')->name('user.edit');
Route::post('update/user', 'UserController@update')->name('user.update');
Route::view('/projekt', 'projekt.index');
Route::get('/editori' , function (){ 
	return \File::get(public_path() . '/index.html');
});
Auth::routes(['verify'=>true]);
/*---------------------------S-----------------------------------------------
| Routes For Articles and The Shopping Cart
|--------------------------------------------------------------------------*/
Route::resource('hause', 'HauseController');
Route::resource('buros', 'BuroController');
Route::resource('baus', 'BauController');
Route::resource('search', 'SearchController');
Route::resource('subcategory', 'SubcategoryController');

/*--------------------------------------------------------------------------
| Routes in which you need to be logged in
|--------------------------------------------------------------------------*/
Route::resource('offers', 'OfferController')->middleware(['auth', 'verified']);
Route::resource('cart', 'CartController')->middleware(['auth', 'verified']);
Route::resource('orders', 'OrderController')->middleware('auth');
Route::resource('favorite', 'FavoriteController')->middleware(['auth', 'verified']);
/*--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------*/
Route::name('admin')->namespace('Admin')->prefix('admin')->middleware(['auth','isadmin' , 'verified'])->group(function () {
	Route::get('/', 'HomeController@index')->name('dashboard');
	Route::resource('admin/objekt','ObjectsController');
	Route::resource('admin/commission','CommissionController');
	Route::resource('articles','ArticleController');
	Route::resource('admin/orders','OrderController');
	Route::resource('admin/offers','OfferController');
	Route::resource('admin/subcategory','SubcategoryController');
	Route::resource('admin/user','UserController');
	Route::get('admin/search', 'SearchController@search')->name('search');
});

resources/views/dashboard.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Impresslight</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{asset('css\skin\frontend\assyrian\uk\css\bootstrap.css')}}" media="all" />
    <link rel="stylesheet" type="text/css" href="{{asset('css\skin\frontend\assyrian\uk\css\bootstrap-theme.css')}}" media="all" />
    <link rel="stylesheet" type="text/css" href="{{asset('css\skin\frontend\assyrian\uk\css\styles.css')}}" media="all" />
    <link rel="stylesheet" type="text/css" href="{{asset('css\skin\frontend\assyrian\uk\magentothem\css\owl.carousel.css')}}" media="all" />
    <link rel="stylesheet" type="text/css" href="{{asset('css\skin\frontend\assyrian\uk\css\font-awesome.css')}}" media="all" />
    <link rel="stylesheet" type="text/css" href="{{asset('css\skin\frontend\assyrian\uk\css\font-awesome.min.css')}}" media="all" />
    <link rel="stylesheet" type="text/css" href="{{asset('css\skin\frontend\base\default\css\widgets.css')}}" media="all" />
    <link rel="stylesheet" type="text/css" href="{{asset('css\skin\frontend\assyrian\uk\css\animate.css')}}" media="all" />
    <link rel="stylesheet" type="text/css" href="{{asset('css\skin\frontend\assyrian\uk\aw_autorelated\cs\category.css')}}" media="all" />
    <link rel="stylesheet" type="text/css" href="{{asset('css\skin\frontend\assyrian\uk\aw_autorelated\css\product.css')}}" media="all" />
    <link rel="stylesheet" type="text/css" href="{{asset('css\skin\frontend\assyrian\uk\css\amshopby.css')}}" media="all" />
    <link rel="stylesheet" type="text/css" href="{{asset('css\skin\frontend\assyrian\uk\magentothem\css\ma_quickview.css')}}" media="all" />
    <link rel="stylesheet" type="text/css" href="{{asset('css\skin\frontend\assyrian\uk\css\skin.css')}}" media="all" />
    <link rel="stylesheet" type="text/css" href="{{asset('css\skin\frontend\assyrian\uk\css\print.css')}}" media="print" />
    <script type="text/javascript" src="../widget.trustpilot.com/bootstrap/v5/tp.widget.sync.bootstrap.min.js"></script>
    <style type="text/css">
    .toplink-contaner {
        opacity: 100%;
        
    }

    #log-in {

        background-color: white;
        padding: 8px;
        color: black;
        text-decoration: none;
        margin: 10px;
        border-radius: 8px;
    }

    #mobile {
        display: none;
    }

    @media (max-width: 640px) {
        #mobile {
            display: block;
            background-color: black;
            opacity: 50%;
            padding: 10px;

        }
        #mobilee {
            display: block;
            margin-left: auto;
            margin-right: auto;
            width: 50%;
            background-color: black;

        }

        #desktop {
            display: none;
        }
    }

    .header {
        margin-left: 10px;
    }

    </style>
</head>

<body class=" cms-index-index cms-assyrian-home cms-assyrian-home">
    <div class="wrapper">
        <div class="page">
            <div id="wrapper">
                <div id="loading" style="position: fixed;top: 50%;left: 50%;margin-top: -50px;"></div>
            </div>
            <div class="header-container">
                <div class="toplink-contaner" id="desktop">
                    <div class="container">
                        <div class="top-link-inner">
                            <div class="box-left">
                                <p class="welcome-msg"> </p>
                                <div class="block-header">
                                    <div class="phone">
                                        <p style=" font-size: 12px; vertical-align: middle;"> +49-123-456</p>
                                    </div>
                                    <div class="email">
                                        <p style="font-size: 12px;"> EMAILIADMINIT@HOTMAIL.COM</p>
                                    </div>
                                </div>
                            </div>
                            <div class="box-right">
                                <div class="language-currency">
                                </div>
                                @if (Auth::check())
                                @if(Auth::user()->isadmin)
                                <div class="top-link" id="top-link">
                                    <div class="select-lang"><a href="{{ url('/admin')}}" title="Home">@lang('messages.home')</a></div>
                                </div>
                                <div class="top-link" id="top-link">
                                    <div class="select-lang"><a href="{{ route('adminarticles.create')}}" title="Home">@lang('messages.createArticle')</a></div>
                                </div>
                                @else
                                <div class="top-link" id="top-link">
                                    <div class="select-lang"><a href="{{ url('/home')}}" title="Home">@lang('messages.home')</a></div>
                                </div>
                                @endif
                                @else
                                @endif
                                @if (Auth::check())
                                <div class="top-link" id="top-link">
                                    <div class="top-link" id="top-link">
                                        <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                            <i class="select-lang"> @lang('messages.logout')</i>
                                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                                @csrf
                                            </form>
                                    </div>
                                </div>
                                @else
                                <div class="top-link" id="top-link">
                                    <div class="select-lang"><a id="log-in" href="{{ route('login' )}}" title="Home">@lang('messages.login')</a></div>
                                </div>
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row" id="mobile">
                    <div class="col">

                        @if (Auth::check())
                        <div class="top-link" id="top-link">
                            <div class="top-link" id="top-link">
                                <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                    <i class="select-lang"> Log out</i>
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                            </div>
                        </div>
                        @else
                        <div class="top-link" id="top-link">
                            <div class="select-lang"><a id="log-in" href="{{ route('login' )}}" title="Home">@lang('messages.login')</a></div>
                        </div>
                        @endif
                    </div>
                    <div class="col">
                        <h2 style="color: white; text-align: center;">ImpressLight</h2>

                    </div>
                </div>
            </div>
            <div class="header" id="mobilee desktop">
                <div class="container">
                    <div class="header-content">
                        <div class="logo-container">
                            <h1 class="logo"><a href="#" title="online-lighting-shop.com" class="logo"><img src="{{asset('img/logo.jpg')}}" style="width:200px;" /></a></h1>
                        </div>
                    <div style="float: right; ">
                               <?php $lang =app()->getLocale(); ?>
                <select onchange="location = this.value;" class="text-uppercase" id="languageCurrent">
                    <option @if($lang == 'de') selected @endif value="/locale/de">DE</option>      
                    <option @if($lang == 'en') selected @endif value="/locale/en">EN</option>      
                    <option @if($lang == 'fr') selected @endif value="/locale/fr">FR</option>
                 </select>
                 </div>
                        </div>
            </div>
        </div>
                    </form>
                    <div class="top-cart-wrapper">
                        <div class="top-cart-contain">
                            <script type="text/javascript">
                            $jq(document).ready(function() {
                                var enable_module = $jq('#enable_module').val();
                                if (enable_module == 0) return false;
                            })

                            </script>
                        </div>
                    </div>
                </div>
            </div>
            <script type="text/javascript">
            $jq(window).scroll(function() {
                if ($jq(this).scrollTop() > 40) {
                    $jq('.header').addClass("fix-header");
                } else {
                    $jq('.header').removeClass("fix-header");
                }
            });

            </script>
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <div class="thumbnail">
                            <h1 style="text-align:center;"> @lang('messages.hause')</h1>
                            <a href="{{ route('hause.index') }}">
                                <img src="{{asset('img/hause.jpg')}}" style="width:100%">
                            </a>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="thumbnail">
                            <h1 style="text-align:center;"> @lang('messages.buro')</h1>
                            <a href="{{ route('buros.index') }}">
                                <img src="{{asset('img/buro.jpg')}}" alt="Nature" style="width:100%;">
                            </a>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="thumbnail">
                            <h1 style="text-align:center;"> @lang('messages.baus')</h1>
                            <a href="{{ route('baus.index') }}">
                                <img src="{{asset('img/baustelle.jpg')}}" alt="Fjords" style="width:47%;">
                                <div class="caption">
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--   -->
    </div>

</html>
</body>

resources/views/home.blade.php
<!DOCTYPE html>
<style>
    .headero {
  padding: 20px;
  text-align: center;
  background: grey;
  color: white;
}
.footer {
  padding: 20px;
  text-align: center;
  background: grey;
  }

    </style>
<html lang="de-CH" class="no-js">

<head>
    <title>KOLICA</title>
    <link rel="stylesheet" href="{{asset('css\app.css')}}">
    <link rel="stylesheet" href="{{asset('css\icons.css')}}">
    <meta name="robots" content="all,noodp">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="application-name" content="Elektrogrosshandel">
    <meta name="theme-color" content="#0083C3">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="csrf-token" content="k8E543y1c8pfewXIGW0kjeSwVS8ejVvAU6aiuCRSCiic0uXQcyvO8sXUDcXYhrAC">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="apple-touch-icon-precomposed" sizes="57x57" href="/static/images/favicon/apple-touch-icon-57x57.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/static/images/favicon/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/static/images/favicon/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/static/images/favicon/apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon-precomposed" sizes="60x60" href="/static/images/favicon/apple-touch-icon-60x60.png">
    <link rel="apple-touch-icon-precomposed" sizes="120x120" href="/static/images/favicon/apple-touch-icon-120x120.png">
    <link rel="apple-touch-icon-precomposed" sizes="76x76" href="/static/images/favicon/apple-touch-icon-76x76.png">
    <link rel="apple-touch-icon-precomposed" sizes="152x152" href="/static/images/favicon/apple-touch-icon-152x152.png">
    <link rel="shortcut icon" type="image/x-icon" href="/static/images/favicon/favicon.ico">
    <link rel="icon" type="image/png" href="/static/images/favicon/favicon-196x196.png" sizes="196x196">
    <link rel="icon" type="image/png" href="/static/images/favicon/favicon-96x96.png" sizes="96x96">
    <link rel="icon" type="image/png" href="/static/images/favicon/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="/static/images/favicon/favicon-16x16.png" sizes="16x16">
    <link rel="icon" type="image/png" href="/static/images/favicon/favicon-128.png" sizes="128x128">
    <meta name="msapplication-config" content="/static/ieconfig.xml">
    <link rel="manifest" href="/static/manifest.webmanifest">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&subset=greek">
    <link rel="stylesheet" type="text/css" href="/static/css/icons.css?f4a2080209ffae2cdba0e">
    <link rel="stylesheet" type="text/css" href="/static/css/app.css?f4a2080209ffae2cdba0e">
    <script>
        var cssLoaded = true;
            </script>
    <script defer src="/static/js/app.js?f4a2080209ffae2cdba0e"></script>
    <link rel="canonical" href="https://www.elektrogrosshandel.ch/de/costcenters/">
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-53269130-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
                        function gtag(){dataLayer.push(arguments);}
                        gtag('js', new Date());
                        gtag('config', 'UA-53269130-1');
                        
                    </script>
</head>

<header class="shopheader">
    <section class="shopheader__middle">
        </a>
        </div>
        <div class="shopheader__search">
            <div class="shopheader__search-instant-results" data-instant-search-results></div>
        </div>
        <section class="shopheader__account">
            <a href="{{ url('/')}}"><i class="icon icon-cart medium"></i>Shopi</a>
            <a href="{{ url('/home') }}" data-toggle="account-menu" title="Mein Konto">
                <i class="icon icon-user medium"></i>
                Kolica
            </a>
            
                <a href="{{ route('logout') }}" onclick="event.preventDefault();
                                                                         document.getElementById('logout-form').submit();">
                    <i class="fa fa-sign-out" style="font-size:20px;color:red"></i>Log Out</a>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
            
            <div class="shopheader-menu shopheader-menu--account dropdown-pane widget" id="account-menu" data-dropdown data-hover="true" data-hover-pane="true" data-position="bottom" data-alignment="right">
                <div class="widget__heading">
                    <form method="POST" class="width-100" action="/de/account/logout/">
                        <input type="hidden" name="csrfmiddlewaretoken" value="QAtYp5OejKarMVrbXLYOQpQwNCxTCyugqyZbPE75JU3oyTrjtntiFDVUvWmDA4zi">
                        <button type="submit" class="button hollow margin-top-1 width-100">
                            <i class="icon icon-logout medium"></i>
                            <span>Abmelden</span>
                        </button>
                    </form>
                </div>
            </div>
            <a href="{{ route('cart.index') }}" title=" " data-toggle="cart-menu" data-bind-prop-set="cart:activeCartLabel,title=Warenkorb {}">
                <i class="icon icon-cart medium"></i>  Shoping Card
                <a href="html.html">
                    <span class="badge hide" data-bind-text="cart:activePositionCount" data-bind-class="cart:isActiveEmpty,hide">
                    </span>
                </a>
                <div class="shopheader-menu shopheader-menu--cart dropdown-pane widget " data-bind-prop-set="cart:hasActivePositions,data-cart-preview=/de/cart/preview" data-cart-preview=/de/cart/preview id="cart-menu" data-dropdown data-hover="true" data-hover-pane="true" data-position="bottom" data-alignment="right">
                    <div class="cart-preview" data-cart-preview-widget>
                        <div class="cart-preview__loader"><i class="icon loader"></i></div>
                        <div class="cart-preview__content" data-bind-innerhtml="cart:preview"></div>
                    </div>
                </div>
        </section>
        </div>
    </section>
    </div>
    </div>
    </div>
    </div>
    </nav>
</header>
<h1 style="text-align:center;">
    Llogaria ime
</h1>
</div>
</header>
<section class="container padding-bottom-3 padding-top-1">
    <div class="grid-x grid-margin-x grid-margin-y" style="justify-content: center;">
        <div class="widget cell small-12 laptop-8 desktop-6 shadow">
            <div class="widget__heading">
                <h5 class="widget__title flex-child-grow">
                    <i class="icon icon-gear"></i>
                    <span>Menaxhimi</span>
                </h5>
            </div>
            <div class="widget__content">
                <div class="grid-x grid-margin-x phablet-up-2">
                    <a href="{{route('commission.index')}}" class="cell margin-bottom-1">
                        <i class="icon icon-list primary medium"></i>
                        <span class="black">
                            Kommissionen
                        </span>
                    </a>
                    <a href="/projekt" class="cell margin-bottom-1">
                        <i class="icon icon-shoppinglist primary medium"></i>
                        <span class="black">
                            Editori
                        </span>
                    </a>
                    <a href="{{ route('cart.index') }}" class="cell margin-bottom-1">
                        <i class="icon icon-carts primary medium"></i>
                        <span class="black">
                            Karrocat e blerjeve
                        </span>
                    </a>
                    
                    <a href="{{ route('offers.index') }}" class="cell margin-bottom-1">
                        <i class="icon icon-offer-doc primary medium"></i>
                        <span class="black">
                            Ofertat
                        </span>
                    </a>
                    <a href="{{route('orders.index')}}" class="cell margin-bottom-1">
                        <i class="icon icon-backorder primary medium"></i>
                        <span class="black">
                            Porosite
                        </span>
                    </a>
                    <a href="{{route('objekt.index')}}" class="cell margin-bottom-1">
                        <i class="icon icon-object primary medium"></i>
                        <span class="black">
                            Menaxhimi i pasurisë
                        </span>
                    </a>
                    <a href="{{ url('/') }}" class="cell margin-bottom-1">
                        <i class="icon icon-object primary medium"></i>
                        <span class="black">
                            Shopi
                        </span>
                    </a>
                </div>
            </div>
        </div>
        <div class="widget cell small-12 laptop-8 desktop-6 shadow">
            <div class="widget__heading">
                <h5 class="widget__title flex-child-grow">
                    <i class="icon icon-user"></i>
                    <span>
                        Të dhënat e përdoruesit dhe kompanisë
                    </span>
                </h5>
            </div>
            <div class="widget__content">
                <div class="grid-x grid-margin-x grid-margin-y phablet-up-2">
                    <div class="cell">
                        <h6 class="widget__subtitle">Nr. i perdoruesit: {{Auth::user()->nr}}</h6>
                        <strong></strong>
                    </div>
                    <div class="cell">
                        <h6 class="widget__subtitle">Perdoruesi: {{Auth::user()->name}}</h6>
                        <strong></strong>
                    </div>
                    <div class="cell">
                        <h6 class="widget__subtitle">Emri i perdoruesit: {{Auth::user()->emri}}</h6>
                        <strong></strong>
                    </div>
                    <div class="cell">
                        <h6 class="widget__subtitle">Roli i autorizimit: Perdorues</h6>
                        <strong></strong>
                    </div>
                    <div class="cell">
                        <h6 class="widget__subtitle">
                            Firma: {{Auth::user()->firma}}
                    </div>
                    <div class="cell">
                        <h6 class="widget__subtitle">E-mail: {{Auth::user()->email,}}</h6>
                        <strong></strong>
                    </div>
                </div>
            </div>
            <div class="widget__footer grid-x grid-margin-y grid-margin-x align-right">
                <div class="cell phablet-shrink phablet-order-2">
                    <a href="{{route('user.edit')}}" class="button phone-down-expanded">
                        <span>redaktoj</span>
                        <i class="icon icon-edit"></i>
                    </a>
                </div>
             
            </div>
        </div>
        <div class="widget cell small-12 laptop-8 desktop-6 shadow">
            <div class="widget__heading">
                <h5 class="widget__title">
                    <i class="icon icon-cart"></i>
                    <span>
                        3 Porositë e fundit</span>
                </h5>
            </div>
            <div class="widget__content">
                <div class="table-scroll">
                    <table class="rows width-100">
                        <thead>
                            <tr>
                                <th data-ordering="name" data-searchable class="">Id</th>
                                <th data-ordering="name" data-searchable class="">Emri i artiku-llit/jve</th>
                                <th data-ordering="comment" data-searchableclass="sortable show-for-tablet">Emri i Perdoruesit</th>
                                <th>Totali</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($orders as $order)
                            <tr>
                                <td>{{$order->id}}</td>
                                <td>{{$order->article_name}}</td>
                                <td>{{$order->user_name}}</td>
                                <td>{{$order->price}}$</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="widget__footer">
                <a href="{{route('orders.index')}}" class="button float-right margin-top-1 phone-down-expanded">
                    <span></span>
                    <i class="icon icon-arrow-right"></i>
                </a>
            </div>
        </div>
    </div>
</section>
</main>

</body>

</html>