routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Route::get('locale/{locale}', function ($locale){
        Session::put('locale', $locale);
        return redirect()->back();
    });
/*--------------------------------------------------------------------------
| User Routes
|--------------------------------------------------------------------------*/
Route::any('/', 'DashboardController@index')->name('Dashboard');
Route::any('/home', 'HomeController@index')->name('Home')->middleware(['auth', 'verified']);
Route::resource('commission','CommissionController')->middleware(['auth', 'verified']);
Route::resource('objekt','ObjectsController')->middleware(['auth', 'verified']);
Route::get('edit/user', 'UserController@edit')->name('user.edit');
Route::post('update/user', 'UserController@update')->name('user.update');
Route::view('/projekt', 'projekt.index');
Route::get('/editori' , function (){ 
	return \File::get(public_path() . '/index.html');
});
Auth::routes(['verify'=>true]);
/*---------------------------S-----------------------------------------------
| Routes For Articles and The Shopping Cart
|--------------------------------------------------------------------------*/
Route::resource('hause', 'HauseController');
Route::resource('buros', 'BuroController');
Route::resource('baus', 'BauController');
Route::resource('search', 'SearchController');
Route::resource('subcategory', 'SubcategoryController');

/*--------------------------------------------------------------------------
| Routes in which you need to be logged in
|--------------------------------------------------------------------------*/
Route::resource('offers', 'OfferController')->middleware(['auth', 'verified']);
Route::resource('cart', 'CartController')->middleware(['auth', 'verified']);
Route::resource('orders', 'OrderController')->middleware('auth');
Route::resource('favorite', 'FavoriteController')->middleware(['auth', 'verified']);
/*--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------*/
Route::name('admin')->namespace('Admin')->prefix('admin')->middleware(['auth','isadmin' , 'verified'])->group(function () {
	Route::get('/', 'HomeController@index')->name('dashboard');
	Route::resource('admin/objekt','ObjectsController');
	Route::resource('admin/commission','CommissionController');
	Route::resource('articles','ArticleController');
	Route::resource('admin/orders','OrderController');
	Route::resource('admin/offers','OfferController');
	Route::resource('admin/subcategory','SubcategoryController');
	Route::resource('admin/user','UserController');
	Route::get('admin/search', 'SearchController@search')->name('search');
});

app/Http/Controllers/Admin/SearchController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Article;
use App\Models\Category;
use App\Models\Subcategory;

class SearchController extends Controller
{
    public function search()
    {
    	$categories = Category::all();
        $subcategories = Subcategory::all();
        $search = \Request::get('search');
        $articles = Article::where('name' , 'like' , '%' .$search. '%')->orWhere('desc' , 'like' , '%' .$search. '%')->orderBy('id')->paginate(8);
        $articles->appends(['search' => $search]);
        return view('admin.search' , compact(['search' , 'articles' , 'categories' , 'subcategories']));
    }
}

app/Http/Controllers/SearchController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Article;
use App\Models\Category;
use App\Models\Subcategory;


class SearchController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('search.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        $subcategories = Subcategory::all();
        $search = \Request::get('search');
        $articles = Article::where('name' , 'like' , '%' .$search. '%')->orWhere('desc' , 'like' , '%' .$search. '%')->orderBy('id')->paginate(6);
        $articles->appends(['search' => $search]);
        return view('search.index' , compact(['search' , 'articles' , 'categories' , 'subcategories']));
        
    }   

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {   
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/search/index.blade.php
<!DOCTYPE html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Search</title>
    <!-- Bootstrap core CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{{ asset('css/shop-homepage.css') }}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{asset('css\skin\frontend\assyrian\uk\css\bootstrap.css')}}" media="all" /> 
    <link rel="stylesheet" type="text/css" href="{{asset('css\skin\frontend\assyrian\uk\css\bootstrap-theme.css')}}" media="all" />
    <link rel="stylesheet" type="text/css" href="{{asset('css\skin\frontend\assyrian\uk\css\styles.css')}}" media="all" />
    <link rel="stylesheet" type="text/css" href="{{asset('css\skin\frontend\assyrian\uk\magentothem\css\owl.carousel.css')}}" media="all" />
    <link rel="stylesheet" type="text/css" href="{{asset('css\skin\frontend\assyrian\uk\css\font-awesome.css')}}" media="all" />
    <link rel="stylesheet" type="text/css" href="{{asset('css\skin\frontend\assyrian\uk\css\font-awesome.min.css')}}" media="all" />
    <link rel="stylesheet" type="text/css" href="{{asset('css\skin\frontend\base\default\css\widgets.css')}}" media="all" />
    <link rel="stylesheet" type="text/css" href="{{asset('css\skin\frontend\assyrian\uk\css\animate.css')}}" media="all" />
    <link rel="stylesheet" type="text/css" href="{{asset('css\skin\frontend\assyrian\uk\aw_autorelated\cs\category.css')}}" media="all" />
    <link rel="stylesheet" type="text/css" href="{{asset('css\skin\frontend\assyrian\uk\aw_autorelated\css\product.css')}}" media="all" />
    <link rel="stylesheet" type="text/css" href="{{asset('css\skin\frontend\assyrian\uk\css\amshopby.css')}}" media="all" />
    <link rel="stylesheet" type="text/css" href="{{asset('css\skin\frontend\assyrian\uk\magentothem\css\ma_quickview.css')}}" media="all" />
    <link rel="stylesheet" type="text/css" href="{{asset('css\skin\frontend\assyrian\uk\css\skin.css')}}" media="all" />
    <link rel="stylesheet" type="text/css" href="{{asset('css\skin\frontend\assyrian\uk\css\print.css')}}" media="print" />
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <style type="text/css">
    
#desktop {display: block;}
#mobile {display: none;}

@media screen and (max-width: 768px) {

#desktop {display: none;}
#mobile {display: block;}
.top-cart-title {
    margin-right: 300px;
}
.form-inline {
    margin-right: 200px
}

}


    
    </style>

</head>

<body>


    <div class="toplink-contaner">
                    <div class="container">
                        <div class="top-link-inner">
                            <div class="box-left">
                                <p class="welcome-msg"> </p>
                                <div class="block-header" id="desktop">
                                    <div class="phone"><label> </label>
                                        <p>+45 252552525</p>
                                    </div>
                                    <div class="email"><label></label>
                                        <p>emailiadminit@hotmail.com</p>
                                    </div>
                                </div>
                            </div>
                            <div class="box-right">
                                <div class="language-currency">
                                </div>
                                <div class="top-link" id="top-link">
                                    <div class="select-lang"><a href="{{ url('/')}}" title="Home">Shopi</a></div>
                                </div>
                                @if (Auth::check())
                                @if(Auth::user()->isadmin)
                                <div class="top-link" id="top-link">
                                    <div class="select-lang"><a href="{{ url('/admin')}}" title="Home">Home</a></div>
                                </div>
                                <div class="top-link" id="top-link">
                                    <div class="select-lang"><a href="{{ route('adminarticles.create')}}" title="Home">Create Article</a></div>
                                </div>
                                @else
                                <div class="top-link" id="top-link">
                                    <div class="select-lang"><a href="{{ url('/home')}}" title="Home">Home</a></div>
                                </div>
                                @endif
                                @else
                                @endif
                                @if (Auth::check())
                                <div class="top-link" id="top-link">
                                    <div class="top-link" id="top-link">
                                        <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                            <i class="select-lang"> Log out</i>
                                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                                @csrf
                                            </form>
                                    </div>
                                </div>
                                @else
                                <div class="top-link" id="top-link">
                                    <div class="select-lang"><a href="{{ route('login' )}}" title="Home">Log in</a></div>
                                </div>
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light" >
  <a class="navbar-brand" href="#" >ImpressLight</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {{ Request::is('hause*') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('hause.index') }}">FUR ZUHAUSE <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {{ Request::is('buros*') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('buros.index') }}">FUR DAS BURO</a>
      </li>
      <li class="nav-item {{ Request::is('baus*') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('baus.index') }}">FUR DIE BAUSTELLE</a>
      </li>
      
      
    </ul>
    <li><form class="form-inline my-2 my-lg-0" style=" float: right;" method="GET" role="search" action="{{route('search.create')}}">
        @csrf
      <input class="form-control mr-sm-2" placeholder="Search" name="search" aria-label="Search" style="margin-top: 5px;">
      
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit" style="margin-top: 5px;" >Search</button>

    </form></li>
    <li>
    <div id="mini_cart_block" style="color: white; float: right; margin-right: 10px" class="items">
                                        <div class="block-cart mini_cart_ajax">
                                            <div class="block-cart">
                                                <div class="top-cart-title">
                                                    <a href="{{ route('cart.index') }}">
                                                        <span class="badge">{{ Cart::count()}}</span>
                                                    </a>
                                                </div>
                                                <div class="top-cart-content">
                                                    <p class="empty">You have no items in your shopping cart.</p>
                                                    <div class="top-subtotal">Subtotal: <span class="price">€0.00</span></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div></li>
  </div>
</nav>
    <!-- Page Content -->
    <div class="container">
        <div class="row">
           
            <!-- /.col-lg-3 -->
            <div class="col-lg-9">
              <div>
                  <h3>Showing results for: {{$search}}. {{$articles->count()}} results found</h3>
              </div>
              <hr>
                   <div class="row">
                        @if($articles->count() > 0)
                    <div class="product-grid-container" >
                        @foreach($articles->chunk(3) as $articleChunk)
                        <ul class="products-grid row" >
                            @csrf
                            @foreach($articleChunk as $article)
                            <li class="ma-item_slider col-sm-4 col-sms-12 item" >
                                <div class="item-inner">
                                    <div class="images-container">
                                        <a href="{{route('hause.show', $article->id)}}" title="01-WL Eindhoven150 – Ace Design" class="product-image"><img src="{{asset('storage/' . $article->image)}}" alt="01-WL Eindhoven150 – Ace Design" max-height="1080" style="width: 560px;height: 300px;" /></a>
                                        <div class="box-hover">
                                            <div class="box-des">
                                            </div>
                                            <div class="actions">
                                                <div class="actions-inner">
                                                    <span class="button btn-cart"><a class="button btn-cart" style="text-decoration: none; color: #ffff; background-color: black" href=" {{route('cart.edit' ,$article->id)}}" title="Add to Cart">Add to cart</a></span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="des-container">
                                        <h2 class="product-name"><a href="{{route("hause.show", $article->id)}}" title="{{$article->company}} | {{$article->name}}"> {{$article->name}}</a></h2>
                                        <ul class="add-to">
                                        <li>{{$article->company}} </li>
                                            
                                        </ul>
                                        <div class="price-box">
                                            <span class="regular-price" id="product-price-17792">
                                                <span class="price">{{$article->price}}$</span>
                                            </span>
                                        </div>
                                        
                                        
                                    </div>
                                </div>
                            </li>
                            @endforeach
                        </ul>
                        @endforeach
                         <div style="text-align: center">
                                {{ $articles->links() }}
                             
                        </div>
                           
                    </div>
                        @else
                        <div style="text-align: center;" class="container"><h2>No results! Please try again.</h2></div>
                        @endif
                </div>
                <!-- /.row -->
            </div>
            <!-- /.col-lg-9 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; ImpressLight 2020</p>
        </div>
        <!-- /.container -->
    </footer>
    <!-- Bootstrap core JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <!-- deri qetu -->


    

    </html>